# Generated by Django 3.0.6 on 2020-07-03 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200627_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileadditional',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofileadditional',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
            preserve_default=False,
        ),
    ]
