# Generated by Django 3.0.6 on 2020-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200703_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileadditional',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
