# Generated by Django 3.0.6 on 2020-06-25 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Brand',
            fields=[
                ('car_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=200)),
                ('license_plate', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('data_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('car_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.Car_Brand')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
