# Generated by Django 3.0.6 on 2020-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20200625_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
