# Generated by Django 3.0.6 on 2020-06-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20200626_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_edited',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
