# Generated by Django 3.0.6 on 2020-07-08 06:28

from django.db import migrations, models
import garage.models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_auto_20200707_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
