# Generated by Django 3.0.6 on 2020-07-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_auto_20200708_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_code',
            new_name='car_brand',
        ),
    ]
