# Generated by Django 3.0.7 on 2020-08-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0022_historicalcar_historicalcar_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_edited',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalCar',
        ),
    ]
