# Generated by Django 3.0.7 on 2020-08-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0024_auto_20200801_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
