# Generated by Django 3.0.7 on 2020-08-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0026_car_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Fee',
            new_name='fee',
        ),
    ]
