# Generated by Django 3.0.7 on 2020-08-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0027_auto_20200802_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCar_Brand',
        ),
    ]
