# Generated by Django 3.0.7 on 2020-08-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0028_delete_historicalcar_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'UnActive')], default=True, null=True),
        ),
    ]
