# Generated by Django 3.0.7 on 2020-08-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0031_auto_20200803_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytrackingcar',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garage.Car'),
        ),
    ]
