# Generated by Django 3.0.7 on 2020-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0032_auto_20200804_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytrackingcar',
            name='action',
            field=models.CharField(choices=[('AD', 'Add'), ('DE', 'Delete'), ('ED', 'Edit')], max_length=2),
        ),
    ]
