# Generated by Django 3.0.7 on 2020-08-04 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0033_auto_20200804_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytrackingcar',
            name='action_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
