# Generated by Django 3.0.7 on 2020-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0034_auto_20200804_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytrackingcar',
            name='car',
        ),
        migrations.AddField(
            model_name='historytrackingcar',
            name='car_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
